version: "3"

# Basic usage:
#     $ docker-compose up
#
# Dev environment (code directory mapped into container):
#     $ docker-compose -f docker-compose.yml -f docker-compose-dev.yml up
#
# Full image (all CLI tools installed):
#     $ docker-compose -f docker-compose.yml -f docker-compose-full.yml up
#
# ASM-NG data resides in a Docker volume
#
#     $ ls -lh /var/lib/docker/volumes/asm-ng_asm-ng-data/_data
#       total 104K
#       drwxr-xr-x 2 user user 4.0K Sep 22 09:51 cache
#       -rw-r--r-- 1 user user 100K Sep 22 15:19 spiderfoot.db

services:
  asm-ng:
    image: ghcr.io/0x31i/asm-ng
    volumes:
      - asm-ng-data:/home/spiderfoot/data
    container_name: asm-ng
    ports:
      - "5001:5001"
      - "8001:8001"
    restart: unless-stopped
    command: ["sf.py", "--both", "-l", "0.0.0.0:5001", "--api-listen", "0.0.0.0:8001"]

  react-web-interface:
    build:
      context: ./react-web-interface
      dockerfile: Dockerfile
    container_name: react-web-interface
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://asm-ng:8000
    depends_on:
      - asm-ng

volumes:
  asm-ng-data:
