services:
  asm-ng:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - asm-ng-data:/home/spiderfoot/data
    image: asm-ng
    container_name: asm-ng
    ports:
      - "5001:5001"
      - "8001:8001"
    restart: unless-stopped

volumes:
  asm-ng-data:
